apiVersion: v1
kind: Namespace
metadata:
 name: sharpeningcloudcomputepod
 labels: { run: "scpodtest" }
---
apiVersion: v1
kind: Pod
metadata:
 namespace: sharpeningcloudcomputepod
 name: sc-compute-deployment
 labels: {run: "scpodtest"}
spec:
  containers:
  - name: sc-compute-container
    image: nginx:1.14.2
    ports:
    - containerPort: 80
